// packages/frontend/src/frontends/react/client/create-root.js
export default length => {
  const n = length - 1;
  const body = Array.from({ length: n }, (_, i) => i - 1)
    .reduceRight((child, _, i) => `components[${i + 1}] !== undefined
        ? createElement(components[${i}], {request, ...data[${i}]}, ${child})
        : createElement(components[${i}], {request, ...data[${i}]})
    `, `createElement(components[${n}], {request, ...data[${n}]})`);

  return `
    import {createElement} from "react";
    import {HeadContext, is} from "@primate/frontend/react";
    const {Provider} = HeadContext;

    export default ({components, data, request, push_heads: value}) =>
      is.client ? ${body} : createElement(Provider, {value}, ${body});
  `;
};

// packages/frontend/src/frontends/solid/client/create-root.js
export default length => {
  const n = length - 1;
  const body = Array.from({ length: n }, (_, i) => i - 1)
    .reduceRight((child, _, i) => `components[${i + 1}] !== undefined
        ? createComponent(components[${i}], {request, ...data[${i}], 
            children: ${child}})
        : createComponent(components[${i}], {request, ...data[${i}]})
    `, `createComponent(components[${n}], {request, ...data[${n}]})`);

  return `
    import {createComponent} from "solid-js/web";
    import {HeadContext, is} from "@primate/frontend/solid";

    const Provider = HeadContext.Provider;

    export default ({components, data, request, push_heads: value}) =>
      is.client ? ${body} : <Provider value={value}>{${body}}</Provider>;
  `;
};
