// packages/react/src/public/head.ts
import HeadContext from "#context/head";
import type Props from "@primate/core/frontend/Props";
import runtime from "@rcompat/runtime";
import React from "react";

const is_client = (runtime === "browser" as any);

type Child = {
  type: string,
  props: Props,
};

const to_array = (maybe: Child[]) => Array.isArray(maybe) ? maybe : [maybe];

const data_attribute = "data-rh";
const data_ssr = "ssr";
const allowed = ["title", "meta", "style", "meta", "link", "script", "base"];

const make_tag = ({ type, props }: Child, id: string) => {
  if (is_client) {
    const element = globalThis.document.createElement(type);
    Object.entries(props).forEach(([name, value]) => {
      element.setAttribute(name, value as string);
    });
    element.dataset.rh = id;
    return element;
  }
  const attributes = Object.entries(props)
    .map(([key, value]) => `${key}="${value}"`)
    .concat(`${data_attribute}="${id}"`)
    .join(" ");

  return `<${type} ${attributes}/>`;
};

const render = (maybe_children: Child[], id: string) => {
  const children = to_array(maybe_children);
  const all_good = children.every(({ type }) => allowed.includes(type));
  if (!all_good) {
    const bad = `<${children.find(({ type }) => !allowed.includes(type))!.type}>`;
    const alloweds = `${allowed.map(tag => `<${tag}>`).join(", ")}`;
    const error = `Head may only contain ${alloweds}, found ${bad}`;
    throw new Error(error);
  }

  const titles = children.filter(({ type }) => type === "title");
  const others = children.filter(({ type }) => type !== "title");

  if (is_client) {
    titles.forEach(title => {
      globalThis.document.title = title.props.children as string;
    });
    others.forEach(other => {
      globalThis.document.head.prepend(make_tag(other, id));
    });
  } else {
    return [
      ...titles.map(title => `<title>${title.props.children}</title>`),
      ...others.map(other => make_tag(other, id)),
    ];
  }
};

const clear = (data_value: string) => {
  const selector = `[${data_attribute}="${data_value}"]`;
  globalThis.document.querySelectorAll(selector).forEach(element => {
    element.remove();
  });
};

const Head = class Head extends React.Component<{ children: Child[] }> {
  declare context: React.ContextType<React.Context<any>>;

  id?: string;
  // clearing after SSR and before root hydration
  static clear(data_value = data_ssr) {
    clear(data_value);
  }

  componentDidMount() {
    if (is_client) {
      this.id = crypto.randomUUID();
      this.props.children
      render(this.props.children, this.id);
    }
  }

  componentDidUpdate() {
    if (is_client) {
      clear(this.id!);
      render(this.props.children, this.id!);
    }
  }

  componentWillUnmount() {
    if (is_client) {
      // remove managed tags
      clear(this.id!);
    }
  }

  render() {
    if (!is_client) {
      this.context(render(this.props.children, data_ssr));
    }

    return undefined as React.ReactNode;
    // no return, nothing rendered
  }
};

Head.contextType = HeadContext;

export default Head;

// packages/solid/src/public/head.ts
import HeadContext from "#context/head";
import type Props from "@primate/core/frontend/Props";
import runtime from "@rcompat/runtime";
import { onCleanup, onMount, useContext } from "solid-js";

const is_client = runtime === "browser" as any;

type ServerElement = {
  t: string;
  tagName: string;
  props: Props;
};

type Tag = HTMLElement | ServerElement;

const to_array = (maybe: Tag[]) => Array.isArray(maybe) ? maybe : [maybe];

const data_attribute = "data-sh";
const data_ssr = "ssr";
const allowed = ["title", "meta", "style", "meta", "link", "script", "base"];

const make_tag = (tag: string, id: string) => {
  const parts = tag.split(" ");
  return [
    parts[0],
    `${data_attribute}="${id}"`,
    ...parts.slice(1),
  ].join(" ");
};

const get_tag = (child: string) => child.match(/^<(?<tag>[a-z]*) .*$/u)?.groups?.tag ?? "";

const render = (maybe_children: Tag[], id: string) => {
  const _children = to_array(maybe_children);

  if (is_client) {
    const children = _children as HTMLElement[]
    // DOM elements
    const titles = children.filter(({ tagName }) => tagName === "TITLE");
    const others = children.filter(({ tagName }) => tagName !== "TITLE");

    titles.forEach(title => {
      globalThis.document.title = title.innerText;
    });
    others.forEach(other => {
      other.dataset.sh = id;
      globalThis.document.head.prepend(other);
    });
  } else {
    const children = _children as ServerElement[];

    const tags = children.map(({ t: tag }) => tag);
    const all_good = tags.every(tag => allowed.includes(get_tag(tag)));
    if (!all_good) {
      const bad = get_tag(tags.find(tag => !allowed.includes(get_tag(tag))) ?? "");
      const alloweds = `${allowed.map(tag => `<${tag}>`).join(", ")}`;
      const error = `Head may only contain ${alloweds}, found <${bad}>`;
      throw new Error(error);
    }

    const titles = tags.filter(tag => get_tag(tag) === "title");
    const others = tags.filter(tag => get_tag(tag) !== "title");

    return [
      ...titles,
      ...others.map(other => make_tag(other, id)),
    ];
  }
};

const clear = (data_value: string) => {
  const selector = `[${data_attribute}="${data_value}"]`;
  globalThis.document.querySelectorAll(selector).forEach(element => {
    element.remove();
  });
};

const Head = function Head(props: { children: Tag[] }) {
  let id: string;
  onMount(() => {
    if (is_client) {
      id = crypto.randomUUID();
      render(props.children, id);
    }
  });

  onCleanup(() => {
    if (is_client) {
      // remove managed tags
      clear(id);
    }
  });

  if (!is_client) {
    const context = useContext(HeadContext);
    context(render(props.children, data_ssr));
  }

  // no return, nothing rendered
};

Head.clear = (data_value = data_ssr) => clear(data_value);

export default Head;
