// packages/react/src/private/head/default.ts
import HeadContext from "#context/head";
import type Props from "@primate/core/frontend/Props";
import React from "react";

type Child = {
  type: string,
  props: Props,
};

const to_array = (maybe: Child[]) => Array.isArray(maybe) ? maybe : [maybe];

const data_attribute = "data-rh";
const data_ssr = "ssr";
const allowed = ["title", "meta", "style", "meta", "link", "script", "base"];

const make_tag = ({ type, props }: Child, id: string) => {
  const attributes = Object.entries(props)
    .map(([key, value]) => `${key}="${value}"`)
    .concat(`${data_attribute}="${id}"`)
    .join(" ");

  return `<${type} ${attributes}/>`;
};

const render = (maybe_children: Child[], id: string) => {
  const children = to_array(maybe_children);
  const all_good = children.every(({ type }) => allowed.includes(type));
  if (!all_good) {
    const bad = `<${children.find(({ type }) => !allowed.includes(type))!.type}>`;
    const alloweds = `${allowed.map(tag => `<${tag}>`).join(", ")}`;
    const error = `Head may only contain ${alloweds}, found ${bad}`;
    throw new Error(error);
  }

  const titles = children.filter(({ type }) => type === "title");
  const others = children.filter(({ type }) => type !== "title");

  return [
    ...titles.map(title => `<title>${title.props.children}</title>`),
    ...others.map(other => make_tag(other, id)),
  ];
};

const clear = (data_value: string) => {
  const selector = `[${data_attribute}="${data_value}"]`;
  globalThis.document.querySelectorAll(selector).forEach(element => {
    element.remove();
  });
};

const Head = class Head extends React.Component<{ children: Child[] }> {
  declare context: React.ContextType<React.Context<any>>;

  id?: string;
  // clearing after SSR and before root hydration
  static clear(data_value = data_ssr) {
    clear(data_value);
  }

  render() {
    this.context(render(this.props.children, data_ssr));

    // no return, nothing rendered
    return undefined as React.ReactNode;
  }
};

Head.contextType = HeadContext;

export default Head;

// packages/solid/src/private/Head/default.ts
import HeadContext from "#context/head";
import type Props from "@primate/core/frontend/Props";
import { useContext, type Context } from "solid-js";

type Child = {
  t: string;
  tagName: string;
  props: Props;
};

const data_attribute = "data-sh";
const data_ssr = "ssr";
const allowed = ["title", "meta", "style", "meta", "link", "script", "base"];

const make_tag = (tag: string, id: string) => {
  const parts = tag.split(" ");
  return [
    parts[0],
    `${data_attribute}="${id}"`,
    ...parts.slice(1),
  ].join(" ");
};

const get_tag = (child: string) => child.match(/^<(?<tag>[a-z]*) .*$/u)?.groups?.tag ?? "";

const render = (children: Child[], id: string) => {
  const tags = children.map(({ t: tag }) => tag);
  const all_good = tags.every(tag => allowed.includes(get_tag(tag)));
  if (!all_good) {
    const bad = get_tag(tags.find(tag => !allowed.includes(get_tag(tag))) ?? "");
    const alloweds = `${allowed.map(tag => `<${tag}>`).join(", ")}`;
    const error = `Head may only contain ${alloweds}, found <${bad}>`;
    throw new Error(error);
  }

  const titles = tags.filter(tag => get_tag(tag) === "title");
  const others = tags.filter(tag => get_tag(tag) !== "title");

  return [
    ...titles,
    ...others.map(other => make_tag(other, id)),
  ];
};

const clear = (data_value: string) => {
  const selector = `[${data_attribute}="${data_value}"]`;
  globalThis.document.querySelectorAll(selector).forEach(element => {
    element.remove();
  });
};

const Head = function Head(props: { children: Child[] }) {
  const context = useContext(HeadContext) as ((input: string[]) => void);
  context(render(props.children, data_ssr));

  // no return, nothing rendered
};

Head.clear = (data_value = data_ssr) => clear(data_value);

export default Head;
